---
http_interactions:
- request:
    method: post
    uri: https://cloudformation.us-east-2.amazonaws.com/
    body:
      encoding: UTF-8
      string: Action=DescribeStacks&StackName=spec-aws-ruby-stack-create-delete-dry&Version=2010-05-15
    headers:
      Content-Type:
      - application/x-www-form-urlencoded; charset=utf-8
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.52.0 ruby/2.5.0 x86_64-darwin17 aws-sdk-cloudformation/1.20.0
      Host:
      - cloudformation.us-east-2.amazonaws.com
      X-Amz-Date:
      - 20191124T154734Z
      X-Amz-Content-Sha256:
      - 778b7e84e12984d834604e0a7e8794e8ababfdebc17c63d330af24cb06d225bb
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20191124/us-east-2/cloudformation/aws4_request,
        SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=<SignatureValue>
      Content-Length:
      - '88'
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      X-Amzn-Requestid:
      - b17c3e6c-431a-4e49-92d1-34f497f2979a
      Content-Type:
      - text/xml
      Content-Length:
      - '323'
      Date:
      - Sun, 24 Nov 2019 15:47:34 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
          <Error>
            <Type>Sender</Type>
            <Code>ValidationError</Code>
            <Message>Stack with id spec-aws-ruby-stack-create-delete-dry does not exist</Message>
          </Error>
          <RequestId>b17c3e6c-431a-4e49-92d1-34f497f2979a</RequestId>
        </ErrorResponse>
    http_version: 
  recorded_at: Sun, 24 Nov 2019 15:47:35 GMT
- request:
    method: post
    uri: https://cloudformation.us-west-2.amazonaws.com/
    body:
      encoding: UTF-8
      string: Action=ValidateTemplate&TemplateBody=Description%3A%20%3E%0A%20%20Test%20template%20one%0A%0AParameters%3A%0A%0A%20%20BucketName%3A%0A%20%20%20%20Type%3A%20String%0A%0A%20%20TagValue%3A%0A%20%20%20%20Type%3A%20String%0A%0AResources%3A%0A%0A%20%20S3Bucket%3A%0A%20%20%20%20Type%3A%20AWS%3A%3AS3%3A%3ABucket%0A%20%20%20%20Properties%3A%0A%20%20%20%20%20%20BucketName%3A%20%21Ref%20%27BucketName%27%0A%20%20%20%20%20%20Tags%3A%0A%20%20%20%20%20%20%20%20-%20Key%3A%20Tag1%0A%20%20%20%20%20%20%20%20%20%20Value%3A%20%21Ref%20%27TagValue%27%0A%0AOutputs%3A%0A%0A%20%20BucketArn%3A%0A%20%20%20%20Value%3A%20%21GetAtt%20%27S3Bucket.Arn%27%0A%20%20%20%20Export%3A%0A%20%20%20%20%20%20Name%3A%20%21Sub%20%27%24%7BAWS%3A%3AStackName%7D-BucketArn%27%0A&Version=2010-05-15
    headers:
      Content-Type:
      - application/x-www-form-urlencoded; charset=utf-8
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.52.0 ruby/2.5.0 x86_64-darwin17 aws-sdk-cloudformation/1.20.0
      Host:
      - cloudformation.us-west-2.amazonaws.com
      X-Amz-Date:
      - 20191124T154735Z
      X-Amz-Content-Sha256:
      - 4c4130d6d8ee21d1264dded763ed8d1415f408345990e0ea0c57bac79465bafc
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20191124/us-west-2/cloudformation/aws4_request,
        SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=<SignatureValue>
      Content-Length:
      - '759'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amzn-Requestid:
      - 4523308f-e5dd-4b31-843b-4e3c7b89cd3b
      Content-Type:
      - text/xml
      Content-Length:
      - '580'
      Date:
      - Sun, 24 Nov 2019 15:47:35 GMT
    body:
      encoding: UTF-8
      string: |
        <ValidateTemplateResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
          <ValidateTemplateResult>
            <Description>Test template one
        </Description>
            <Parameters>
              <member>
                <ParameterKey>BucketName</ParameterKey>
                <NoEcho>false</NoEcho>
              </member>
              <member>
                <ParameterKey>TagValue</ParameterKey>
                <NoEcho>false</NoEcho>
              </member>
            </Parameters>
          </ValidateTemplateResult>
          <ResponseMetadata>
            <RequestId>4523308f-e5dd-4b31-843b-4e3c7b89cd3b</RequestId>
          </ResponseMetadata>
        </ValidateTemplateResponse>
    http_version: 
  recorded_at: Sun, 24 Nov 2019 15:47:35 GMT
- request:
    method: put
    uri: https://openstax-sandbox-cfn-templates.s3.us-west-2.amazonaws.com/cfn_templates/spec-templates/template_one.yml
    body:
      encoding: UTF-8
      string: |
        Description: >
          Test template one

        Parameters:

          BucketName:
            Type: String

          TagValue:
            Type: String

        Resources:

          S3Bucket:
            Type: AWS::S3::Bucket
            Properties:
              BucketName: !Ref 'BucketName'
              Tags:
                - Key: Tag1
                  Value: !Ref 'TagValue'

        Outputs:

          BucketArn:
            Value: !GetAtt 'S3Bucket.Arn'
            Export:
              Name: !Sub '${AWS::StackName}-BucketArn'
    headers:
      Content-Type:
      - ''
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.52.0 ruby/2.5.0 x86_64-darwin17 aws-sdk-s3/1.37.0
      Expect:
      - 100-continue
      Content-Md5:
      - iwRQXuudefxiuYnuy/AKYA==
      Host:
      - openstax-sandbox-cfn-templates.s3.us-west-2.amazonaws.com
      X-Amz-Date:
      - 20191124T154735Z
      X-Amz-Content-Sha256:
      - 44820f5081bfdd4c387cf15b34f8f70367dbba4e87e0c51380353e1b3b436eab
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20191124/us-west-2/s3/aws4_request,
        SignedHeaders=content-md5;expect;host;user-agent;x-amz-content-sha256;x-amz-date,
        Signature=<SignatureValue>
      Content-Length:
      - '395'
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Amz-Id-2:
      - 2abr7LOkZ95FaI5wcCIKAvD1waQQDkSgkUhxQokz5za6zkds3qSII9WHWVMXT+oU7rbI5Cpn4hE=
      X-Amz-Request-Id:
      - 3527785D9715CF87
      Date:
      - Sun, 24 Nov 2019 15:47:36 GMT
      X-Amz-Version-Id:
      - zZup6HTlHUFCjVc9jLHjFUfq9rV12d1W
      X-Amz-Server-Side-Encryption:
      - AES256
      Etag:
      - '"8b04505eeb9d79fc62b989eecbf00a60"'
      Content-Length:
      - '0'
      Server:
      - AmazonS3
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Sun, 24 Nov 2019 15:47:35 GMT
- request:
    method: post
    uri: https://cloudformation.us-east-2.amazonaws.com/
    body:
      encoding: UTF-8
      string: Action=DescribeStacks&StackName=spec-aws-ruby-stack-create-delete-dry&Version=2010-05-15
    headers:
      Content-Type:
      - application/x-www-form-urlencoded; charset=utf-8
      Accept-Encoding:
      - ''
      User-Agent:
      - aws-sdk-ruby3/3.52.0 ruby/2.5.0 x86_64-darwin17 aws-sdk-cloudformation/1.20.0
      Host:
      - cloudformation.us-east-2.amazonaws.com
      X-Amz-Date:
      - 20191124T154735Z
      X-Amz-Content-Sha256:
      - 778b7e84e12984d834604e0a7e8794e8ababfdebc17c63d330af24cb06d225bb
      Authorization:
      - AWS4-HMAC-SHA256 Credential=AWS_ACCESS_KEY_ID/20191124/us-east-2/cloudformation/aws4_request,
        SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=<SignatureValue>
      Content-Length:
      - '88'
      Accept:
      - "*/*"
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      X-Amzn-Requestid:
      - f685cbea-d8f9-4d90-9f91-b1e48ac28e67
      Content-Type:
      - text/xml
      Content-Length:
      - '323'
      Date:
      - Sun, 24 Nov 2019 15:47:35 GMT
      Connection:
      - close
    body:
      encoding: UTF-8
      string: |
        <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
          <Error>
            <Type>Sender</Type>
            <Code>ValidationError</Code>
            <Message>Stack with id spec-aws-ruby-stack-create-delete-dry does not exist</Message>
          </Error>
          <RequestId>f685cbea-d8f9-4d90-9f91-b1e48ac28e67</RequestId>
        </ErrorResponse>
    http_version: 
  recorded_at: Sun, 24 Nov 2019 15:47:36 GMT
recorded_with: VCR 4.0.0
