Description: >
  Test template one mod

Parameters:

  BucketName:
    Type: String

  TagValue:
    Type: String

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'BucketName'
      Tags:
        - Key: Tag1
          Value: !Ref 'TagValue'

Outputs:

  BucketArnMod:
    Value: !GetAtt 'S3Bucket.Arn'
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
