Description: >
  aws-ruby spec template - updating_parameters - orig

Parameters:

  WillGoAway:
    Type: String

  SticksAround:
    Type: String

  SticksAroundNoDefault:
    Type: String

  VolatileValue:
    Type: String

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: openstax-aws-ruby-spec-param-updates
      Tags:
        - Key: Tag1
          Value: !Ref 'VolatileValue'
