name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Test
        run: bundle exec rspec
